name: build

# CINTENT >> MANUAL_TRIGGER
# on:
#   push:
#     branches: ["dev"]
#     tags: ["*"]
#   pull_request:
on: [repository_dispatch, workflow_dispatch]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # CINTENT >> REMOVE_MATRIX
          # - { name: "3.9", python: "3.9", tox: py39 }
          # - { name: "lowest", python: "3.9", tox: py39-lowest }
          - { name: "3.13", python: "3.13", tox: py313 }
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Download nltk data
        run: |
          pip install .
          python -m textblob.download_corpora

      - run: python -m pip install tox

      - run: python -m tox -e${{ matrix.tox }}

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Install pypa/build
        run: python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build

      - name: Install twine
        run: python -m pip install twine

      - name: Check build
        run: python -m twine check --strict dist/*

      # CINTENT >> REMOVE_UPLOADS
      # - name: Store the distribution packages
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: python-package-distributions
      #     path: dist/

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

  # this duplicates pre-commit.ci, so only run it on tags
  # it guarantees that linting is passing prior to a release
  lint-pre-release:
    # CINTENT >> REMOVE_TRIGGER
    # if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - run: python -m pip install tox

      - run: python -m tox -e lint
  
      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

  # CINTENT >> NOT_CI
  # publish-to-pypi:
  #   name: PyPI release
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: [build, tests, lint-pre-release]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/textblob
  #   permissions:
  #     id-token: write
  #   steps:
  #     - name: Download all the dists
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: python-package-distributions
  #         path: dist/
  #     - name: Publish distribution to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
